[tool.ruff]
line-length = 79
indent-width = 4
format.quote-style = "single"
analyze.detect-string-imports = true

[tool.ruff.lint]
select = ["E", "F", "TID25", "I", "N", "C901"]
ignore = ["F811", "D100", "D107", "D203", "D205", "D213", "D400", "D401", "N806", "N818"]
mccabe.max-complexity = 10

[tool.ty.rules]
unresolved-import = "ignore"

[tool.basedpyright]
reportUnusedCallResult = "none"

